# Generated by Django 5.0.6 on 2024-07-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='arrendador',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='arrendado',
            field=models.BooleanField(default=False),
        ),
    ]
