# Generated by Django 5.0.6 on 2024-07-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadl', '0004_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('libros', models.ManyToManyField(related_name='autores', to='testadl.libro')),
            ],
        ),
    ]
