# Generated by Django 5.0.6 on 2024-07-01 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testadl', '0005_libro_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(max_length=50)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testadl.autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testadl.libro')),
            ],
        ),
    ]
